### ISSUE TITLE
parcel gives error when try to run the code

### ISSUE THREAD

**Issue by Casburggraaf** [meesrutten/wafs#1]
```
➜  app git:(patch-1) ✗ npm install -g parcel-bundler
/Users/cas/.nvm/versions/node/v8.9.4/bin/parcel -> /Users/cas/.nvm/versions/node/v8.9.4/lib/node_modules/parcel-bundler/bin/cli.js

> fsevents@1.1.3 install /Users/cas/.nvm/versions/node/v8.9.4/lib/node_modules/parcel-bundler/node_modules/fsevents
> node install

[fsevents] Success: "/Users/cas/.nvm/versions/node/v8.9.4/lib/node_modules/parcel-bundler/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> parcel-bundler@1.5.1 postinstall /Users/cas/.nvm/versions/node/v8.9.4/lib/node_modules/parcel-bundler
> node -e "console.log('\u001b[35m\u001b[1mLove Parcel? You can now donate to our open collective:\u001b[22m\u001b[39m\n > \u001b[34mhttps://opencollective.com/parcel/donate\u001b[0m')"

Love Parcel? You can now donate to our open collective:
 > https://opencollective.com/parcel/donate
+ parcel-bundler@1.5.1
added 770 packages in 11.413s
➜  app git:(patch-1) ✗ parcel index.html            
Server running at http://localhost:1234 
🚨  Cannot find module '/Users/cas/Develop/webdev/wafs/app/index.html' from '.'
    at /Users/cas/.nvm/versions/node/v8.9.4/lib/node_modules/parcel-bundler/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/Users/cas/.nvm/versions/node/v8.9.4/lib/node_modules/parcel-bundler/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/cas/.nvm/versions/node/v8.9.4/lib/node_modules/parcel-bundler/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/cas/.nvm/versions/node/v8.9.4/lib/node_modules/parcel-bundler/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
```

**Comment by meesrutten** [comment]
Should have been `parcel src/index.html` 
Fixed
